steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/trud-api/gcpcloudbuilddemo/gcpcloudbuilddemo-service:latest',  '.']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/trud-api/gcpcloudbuilddemo/gcpcloudbuilddemo-service:latest']

images: ['us-central1-docker.pkg.dev/trud-api/gcpcloudbuilddemo/gcpcloudbuilddemo-service:latest']



options:
  logging: CLOUD_LOGGING_ONLY